apiVersion: v1
kind: Service
metadata:
  name: servicemesh-consul
  labels:
    app: servicemesh
spec:
  type: LoadBalancer 
  
  # todo: what is the targetPort attribute?
  ports:
  - name: talk-to-other-agents
    port: 8300
    targetPort: 8300
  - name: handle-gossip-in-the-lan
    port: 8301
    targetPort: 8301
  - name: http-api
    port: 8500
    targetPort: 8500
  - name: dns-interface    
    port: 8600
    targetPort: 8600

  selector:
    app: servicemesh

---

apiVersion: v1
kind: Service
metadata:
  name: servicemesh-linkerd
  labels:
    app: servicemesh
spec:
  type: LoadBalancer
  
  
  ports:
  - name: linkerd-admin
    port: 9990
    targetPort: 9990
    
  - name: operations
    port: 4140
    targetPort: 4140

  selector:
    app: servicemesh

---

apiVersion: v1
kind: Service
metadata:
  name: servicemesh-zipkin
  labels:
    app: servicemesh
spec:
  type: LoadBalancer
  
  # todo: what is the targetPort attribute?
  ports:
  - name: scribe
    port: 9410
    targetPort: 9410
  - name: http
    port: 9411
    targetPort: 9411

  selector:
    app: servicemesh
---
apiVersion: v1
kind: Service
metadata:
  name: servicemesh-linkerd-viz
  labels:
    app: servicemesh
spec:
  type: LoadBalancer
  externalName: linkerd-viz
  
  # todo: what is the targetPort attribute?
  ports:
  - name: main-ui
    port: 3000
    targetPort: 3000
    
  - name: prometheous
    port: 9191
    targetPort: 9191

  selector:
    app: servicemesh

