kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: uid1000
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  storageAccount: surferstorageacct

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: uid100
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=100
  - gid=100
parameters:
  skuName: Standard_LRS
  storageAccount: surferstorageacct

